version: 2
jobs:
  build:
    docker:
      - image: alpine
    steps:
      # Setup
      - checkout
      - run: "apk update && apk add --no-cache python3 py3-pip && pip3 install pylint"

      # Pylint
      - run: "pylint -d import-error **/**.py"
